export const initialWordList = [
  {
    id: 1,
    japanese: "宇宙",
    furigana: "うちゅう",
    meaning: "space/universe",
  },
  {
    id: 2,
    japanese: "革命",
    furigana: "かくめい",
    meaning: "revolution",
  },
  {
    id: 3,
    japanese: "未来",
    furigana: "みらい",
    meaning: "future",
  },
  {
    id: 4,
    japanese: "文明",
    furigana: "ぶんめい",
    meaning: "civilization",
  },
  {
    id: 5,
    japanese: "環境",
    furigana: "かんきょう",
    meaning: "environment",
  },
  {
    id: 6,
    japanese: "技術",
    furigana: "ぎじゅつ",
    meaning: "technology",
  },
  {
    id: 7,
    japanese: "発展",
    furigana: "はってん",
    meaning: "development",
  },
  {
    id: 8,
    japanese: "経済",
    furigana: "けいざい",
    meaning: "economy",
  },
  {
    id: 9,
    japanese: "政治",
    furigana: "せいじ",
    meaning: "politics",
  },
  {
    id: 10,
    japanese: "社会",
    furigana: "しゃかい",
    meaning: "society",
  },
  {
    id: 11,
    japanese: "愛",
    furigana: "あい",
    meaning: "love",
  },
  {
    id: 12,
    japanese: "自由",
    furigana: "じゆう",
    meaning: "freedom",
  },
  {
    id: 13,
    japanese: "平和",
    furigana: "へいわ",
    meaning: "peace",
  },
  {
    id: 14,
    japanese: "希望",
    furigana: "きぼう",
    meaning: "hope",
  },
  {
    id: 15,
    japanese: "友情",
    furigana: "ゆうじょう",
    meaning: "friendship",
  },
  {
    id: 16,
    japanese: "教育",
    furigana: "きょういく",
    meaning: "education",
  },
  {
    id: 17,
    japanese: "文化",
    furigana: "ぶんか",
    meaning: "culture",
  },
  {
    id: 18,
    japanese: "科学",
    furigana: "かがく",
    meaning: "science",
  },
  {
    id: 19,
    japanese: "歴史",
    furigana: "れきし",
    meaning: "history",
  },
  {
    id: 20,
    japanese: "健康",
    furigana: "けんこう",
    meaning: "health",
  },
  {
    id: 21,
    japanese: "幸福",
    furigana: "こうふく",
    meaning: "happiness",
  },
  {
    id: 22,
    japanese: "冒険",
    furigana: "ぼうけん",
    meaning: "adventure",
  },
  {
    id: 23,
    japanese: "知識",
    furigana: "ちしき",
    meaning: "knowledge",
  },
  {
    id: 24,
    japanese: "自然",
    furigana: "しぜん",
    meaning: "nature",
  },
  {
    id: 25,
    japanese: "旅",
    furigana: "たび",
    meaning: "journey",
  },
  {
    id: 26,
    japanese: "芸術",
    furigana: "げいじゅつ",
    meaning: "art",
  },
  {
    id: 27,
    japanese: "音楽",
    furigana: "おんがく",
    meaning: "music",
  },
  {
    id: 28,
    japanese: "夢",
    furigana: "ゆめ",
    meaning: "dream",
  },
  {
    id: 29,
    japanese: "時間",
    furigana: "じかん",
    meaning: "time",
  },
]
