export const initialWordList = [
  {
    id: 1,
    japanese: "宇宙",
    furigana: "うちゅう",
    meaning: "space/universe",
  },
  {
    id: 2,
    japanese: "革命",
    furigana: "かくめい",
    meaning: "revolution",
  },
  {
    id: 3,
    japanese: "未来",
    furigana: "みらい",
    meaning: "future",
  },
  {
    id: 4,
    japanese: "文明",
    furigana: "ぶんめい",
    meaning: "civilization",
  },
  {
    id: 5,
    japanese: "環境",
    furigana: "かんきょう",
    meaning: "environment",
  },
  {
    id: 6,
    japanese: "技術",
    furigana: "ぎじゅつ",
    meaning: "technology",
  },
  {
    id: 7,
    japanese: "発展",
    furigana: "はってん",
    meaning: "development",
  },
  {
    id: 8,
    japanese: "経済",
    furigana: "けいざい",
    meaning: "economy",
  },
  {
    id: 9,
    japanese: "政治",
    furigana: "せいじ",
    meaning: "politics",
  },
  {
    id: 10,
    japanese: "社会",
    furigana: "しゃかい",
    meaning: "society",
  },
  {
    id: 11,
    japanese: "愛",
    furigana: "あい",
    meaning: "love",
  },
  {
    id: 12,
    japanese: "自由",
    furigana: "じゆう",
    meaning: "freedom",
  },
  {
    id: 13,
    japanese: "平和",
    furigana: "へいわ",
    meaning: "peace",
  },
  {
    id: 14,
    japanese: "希望",
    furigana: "きぼう",
    meaning: "hope",
  },
  {
    id: 15,
    japanese: "友情",
    furigana: "ゆうじょう",
    meaning: "friendship",
  },
]
